language: cpp

sudo: required
dist: trusty

compiler:
  - gcc
  - clang

before_install:
  - sudo apt-get install -qq cmake libboost-regex-dev

before_script:
  - mkdir build
  - cd build
  - cmake -DOPTION_BUILD_EXAMPLES=On -DOPTION_BUILD_WITH_STD_REGEX=Off ..

script:
  - make -j8
  - make test
